# Uygulamanın çalışacağı port (Varsayılan 8080)
server.port=8080

# ==========================================
# SUPABASE POSTGRESQL VERİTABANI BAĞLANTISI
# ==========================================
# NOT: Supabase panelinde Settings -> Database kısmındaki "Connection String" -> JDBC alanından bu bilgileri alabilirsin.
spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
spring.datasource.username=postgres.rpugcpclwembabwebrxy
spring.datasource.password=7CrFwKU8NXVPk5e8
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Ayarları (Tabloları Java modellerine göre otomatik günceller/oluşturur)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# ==========================================
# SUPABASE JWT GÜVENLİK SIRRI (SECRET)
# ==========================================
# NOT: Supabase panelinde Settings -> API kısmındaki "JWT Secret" alanındaki koca şifredir.
supabase.jwt.secret=8VGnk5N5Q16gmsmXtGokPUW/FNSzDoAoN8/t8vGq+ZsDtzStbznjG6Ciy1cbzBy4bqBHkfeL/YTsE4jSOV9Xjg==
server.address=0.0.0.0